src/main/java/br/usp/ime/vision/dataset/entities/Album.java
package br.usp.ime.vision.dataset.entities;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import br.usp.ime.vision.dataset.dao.DAOFactory;
import br.usp.ime.vision.dataset.util.Constants;
import br.usp.ime.vision.dataset.util.Messages;

/**
 * Represents an {@link Album} that can contain {@link Image}s and other
 * {@link Album}s.
 * 
 * @author Bruno Klava
 */
public class Album {

    /**
     * Returns the <code>String</code> representation of an {@link Album}
     * <code>createPermission</code>.
     * 
     * @return the <code>String</code> representation of an {@link Album}
     *         <code>createPermission</code>
     */
    public static String getCreatePermissionString(final int createPermission) {
        switch (createPermission) {
        case Constants.ALBUM_USERS_CREATE:
            return Messages.getMessage("album.permission.create.users");
        default:
        case Constants.ALBUM_PRIVATE_CREATE:
            return Messages.getMessage("album.permission.create.private");
        }
    }

    /**
     * Returns the <code>String</code> representation of an {@link Album}
     * <code>viewPermission</code>.
     * 
     * @return the <code>String</code> representation of an {@link Album}
     *         <code>viewPermission</code>
     */
    public static String getViewPermissionString(final int viewPermission) {
        switch (viewPermission) {
        case Constants.ALBUM_PUBLIC_VIEW:
            return Messages.getMessage("album.permission.view.public");
        case Constants.ALBUM_USERS_VIEW:
            return Messages.getMessage("album.permission.view.users");
        default:
        case Constants.ALBUM_PRIVATE_VIEW:
            return Messages.getMessage("album.permission.view.private");
        }
    }

    private int id;

    private String name;

    private int ownerId;

    private Date dateCreation;

    private Date dateUpdate;

    private List<Image> images;

    private int viewPermission;

    private int createPermission;

    private List<Album> subAlbums;

    protected List<Album> parents;

    private List<Album> albumsChain;

    private List<Tag> tags;

    /**
     * Deletes this {@link Album} and all the {@link Album}s and {@link Image}s
     * under this {@link Album} hierarchy
     * 
     * @return <code>true</code> if the {@Album} deletion was successful
     */
    public boolean deleteAlbum() {

        for (final Album subAlbum : getSubAlbums()) {
            if (!subAlbum.deleteAlbum()) {
                return false;
            }
        }

        for (final Image image : getImages()) {
            if (!image.deleteImage()) {
                return false;
            }
        }

        return DAOFactory.getAlbumDao().deleteAlbum(getId());

    }

    /**
     * Returns a <code>List</code> with all the {@link Album}s from the
     * hierarchy root to this {@link Album}.
     * 
     * @return the parents of this {@link Album}
     */
    public List<Album> getAlbumsChain() {
        if (albumsChain == null) {
            albumsChain = new ArrayList<Album>();
            albumsChain.addAll(getParents());
            albumsChain.add(this);
        }
        return albumsChain;
    }

    public int getCreatePermission() {
        return createPermission;
    }

    /**
     * Returns the <code>String</code> representation of this {@link Album}
     * <code>createPermission</code>.
     * 
     * @return the <code>String</code> representation of this {@link Album}
     *         <code>createPermission</code>
     */
    public String getCreatePermissionString() {
        return getCreatePermissionString(createPermission);
    }

    public Date getDateCreation() {
        return dateCreation;
    }

    public Date getDateUpdate() {
        return dateUpdate;
    }

    public int getId() {
        return id;
    }

    public List<Image> getImages() {
        if (images == null) {
            images = DAOFactory.getAlbumDao().getImages(getId());
        }
        return images;
    }

    public String getName() {
        return name;
    }

    public int getOwnerId() {
        return ownerId;
    }

    /**
     * Returns a <code>List</code> with the parent {@link Album}s of this
     * {@link Album}.
     * 
     * @return the parents of this {@link Album}
     */
    public List<Album> getParents() {
        if (parents == null) {
            parents = new ArrayList<Album>();
        }
        return parents;
    }

    /**
     * Returns the {@link Album}s that is the root of the hierarchy that this
     * {@link Album} belongs to.
     * 
     * @return the hierarchy root of this {@link Album}
     */
    public Album getRootAlbum() {
        return getAlbumsChain().get(0);
    }

    /**
     * Returns the {@link Album}s that is the root of the hierarchy that this
     * {@link Album} belongs to.
     * 
     * @return the hierarchy root of this {@link Album}
     */
    public List<Album> getSubAlbums() {
        if (subAlbums == null) {
            subAlbums = DAOFactory.getAlbumDao().getSubAlbums(getId());
        }
        return subAlbums;
    }

    public List<Tag> getTags() {
        if (tags == null) {
            tags = DAOFactory.getTagDao().getAlbumTags(getId());
        }
        return tags;
    }

    public int getViewPermission() {
        return viewPermission;
    }

    /**
     * Returns the <code>String</code> representation of this {@link Album}
     * <code>viewPermission</code>.
     * 
     * @return the <code>String</code> representation of this {@link Album}
     *         <code>viewPermission</code>
     */
    public String getViewPermissionString() {
        return getViewPermissionString(viewPermission);
    }

    /**
     * Returns if this {@link Album} doesn't contain any {@link Album}s nor
     * {@link Image}s.
     * 
     * @return <code>true</code> if this {@link Album} doesn't contain any
     *         {@link Album}s nor {@link Image}s
     */
    public boolean isEmptyAlbum() {
        return getImages().isEmpty() && getSubAlbums().isEmpty();
    }

    /**
     * Returns if this {@link Album} has {@link Constants.ALBUM_PUBLIC_VIEW}
     * <code>viewPermission</code>.
     * 
     * @return <code>true</code> if this {@link Album} has
     *         {@link Constants.ALBUM_PUBLIC_VIEW} <code>viewPermission</code>
     */
    public boolean isPublicView() {
        return getViewPermission() == Constants.ALBUM_PUBLIC_VIEW;
    }

    /**
     * Returns if this {@link Album} has {@link Constants.ALBUM_PRIVATE_CREATE}
     * <code>createPermission</code>.
     * 
     * @return <code>true</code> if this {@link Album} has
     *         {@link Constants.ALBUM_PRIVATE_CREATE}
     *         <code>createPermission</code>
     */
    public boolean isRestrictedCreate() {
        return getCreatePermission() == Constants.ALBUM_PRIVATE_CREATE;
    }

    /**
     * Returns if this {@link Album} has {@link Constants.ALBUM_PRIVATE_VIEW}
     * <code>viewPermission</code>.
     * 
     * @return <code>true</code> if this {@link Album} has
     *         {@link Constants.ALBUM_PRIVATE_VIEW} <code>viewPermission</code>
     */
    public boolean isRestrictedView() {
        return getViewPermission() == Constants.ALBUM_PRIVATE_VIEW;
    }

    /**
     * Returns if this {@link Album} is the root of its hierarchy.
     * 
     * @return <code>true</code> if this {@link Album} is the root of its
     *         hierarchy
     */
    public boolean isRootAlbum() {
        return true;
    }

    /**
     * Returns if this {@link Album} has {@link Constants.ALBUM_USERS_CREATE}
     * <code>createPermission</code>.
     * 
     * @return <code>true</code> if this {@link Album} has
     *         {@link Constants.ALBUM_USERS_CREATE}
     *         <code>createPermission</code>
     */
    public boolean isUsersCreate() {
        return getCreatePermission() == Constants.ALBUM_USERS_CREATE;
    }

    /**
     * Returns if this {@link Album} has {@link Constants.ALBUM_USERS_VIEW}
     * <code>viewPermission</code>.
     * 
     * @return <code>true</code> if this {@link Album} has
     *         {@link Constants.ALBUM_USERS_VIEW} <code>viewPermission</code>
     */
    public boolean isUsersView() {
        return getViewPermission() == Constants.ALBUM_USERS_VIEW;
    }

    public void setCreatePermission(final int createPermission) {
        this.createPermission = createPermission;
    }

    public void setDateCreation(final Date dateCreation) {
        this.dateCreation = dateCreation;
    }

    public void setDateUpdate(final Date dateUpdate) {
        this.dateUpdate = dateUpdate;
    }

    public void setId(final int id) {
        this.id = id;
    }

    public void setName(final String name) {
        this.name = name;
    }

    public void setOwnerId(final int ownerId) {
        this.ownerId = ownerId;
    }

    public void setViewPermission(final int viewPermission) {
        this.viewPermission = viewPermission;
    }

    @Override
    public String toString() {
        return "Album [id=" + id + ", name=" + name + ", ownerId=" + ownerId
                + ", dateCreation=" + dateCreation + ", dateUpdate="
                + dateUpdate + ", viewPermission=" + getViewPermissionString()
                + ", createPermission=" + getCreatePermissionString() + "]";
    }

}

src/main/java/br/usp/ime/vision/dataset/entities/ImageTag.java
package br.usp.ime.vision.dataset.entities;

import br.usp.ime.vision.dataset.dao.DAOFactory;

/**
 * Represents an {@link Tag} associated to an {@link Image}.
 * 
 * @author Bruno Klava
 */
public class ImageTag extends Tag {

    private int imageId;

    @Override
    public boolean deleteTag() {
        return DAOFactory.getTagDao().deleteImageTag(getImageId(), getId());
    }

    public int getImageId() {
        return imageId;
    }

    public void setImageId(final int imageId) {
        this.imageId = imageId;
    }

    @Override
    public String toString() {
        return "ImageTag [" + getTagName() + ", id=" + getId() + ", imageId="
                + imageId + "]";
    }

}

src/main/java/br/usp/ime/vision/dataset/entities/User.java
package br.usp.ime.vision.dataset.entities;

import java.util.Date;

import br.usp.ime.vision.dataset.util.Constants;
import br.usp.ime.vision.dataset.util.CryptoUtils;
import br.usp.ime.vision.dataset.util.Messages;

/**
 * Represents an {@link User} in the system.
 * 
 * @author Bruno Klava
 */
public class User {

    /**
     * Returns the <code>String</code> representation of an {@link User}
     * <code>permission</code>.
     * 
     * @return the <code>String</code> representation of an {@link User}
     *         <code>permission</code>
     */
    public static String getPermissionString(final int permission) {
        switch (permission) {
        case Constants.ADMIN_PERMISSION:
            return Messages.getMessage("permission.admin");
        case Constants.CREATE_PERMISSION:
            return Messages.getMessage("permission.create");
        default:
        case Constants.VIEW_PERMISSION:
            return Messages.getMessage("permission.view");
        }
    }

    private int id;

    private String username;

    private String name;

    private String email;

    private boolean emailConfirmed;

    private boolean accountAuthorized;

    private String password;

    private Date dateCreation;

    private Date dateUpdate;

    private int permission;

    private boolean active;

    public User() {

    }

    /**
     * Generates the confirmation code (derived from <code>email</code> and
     * <code>password</code>) associated to this {@link User}.
     * 
     * @return the confirmation code (derived from <code>email</code> and
     *         <code>password</code>) associated to this {@link User}
     */
    public String getConfirmationCode() {
        return CryptoUtils.encrypt(getEmail() + getPassword());
    }

    public Date getDateCreation() {
        return dateCreation;
    }

    public Date getDateUpdate() {
        return dateUpdate;
    }

    /**
     * Returns an <code>String</code> description of this {@link User}.
     * 
     * @return an <code>String</code> description of this {@link User}
     */
    public String getDescription() {
        return getName() + " (" + getUsername() + ") " + getEmail();
    }

    public String getEmail() {
        return email;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getPassword() {
        return password;
    }

    public int getPermission() {
        return permission;
    }

    /**
     * Returns the <code>String</code> representation of this {@link User}
     * <code>permission</code>.
     * 
     * @return the <code>String</code> representation of this {@link User}
     *         <code>permission</code>
     */
    public String getPermissionString() {
        return getPermissionString(permission);
    }

    // TODO refactor the view to use fn and remove this method
    public String getPermissionStringLowerCase() {
        return getPermissionString().toLowerCase();
    }

    public String getUsername() {
        return username;
    }

    public boolean isAccountAuthorized() {
        return accountAuthorized;
    }

    public boolean isActive() {
        return active;
    }

    /**
     * Returns if this {@link User} has {@link Constants.ADMIN_PERMISSION}
     * <code>permission</code>.
     * 
     * @return <code>true</code> if this {@link User} has
     *         {@link Constants.ADMIN_PERMISSION} <code>permission</code>
     */
    public boolean isAdmin() {
        return permission == Constants.ADMIN_PERMISSION;
    }

    /**
     * Returns if this {@link User} has {@link Constants.CREATE_PERMISSION}
     * <code>permission</code>.
     * 
     * @return <code>true</code> if this {@link User} has
     *         {@link Constants.CREATE_PERMISSION} <code>permission</code>
     */
    public boolean isCreatePermission() {
        return permission >= Constants.CREATE_PERMISSION;
    }

    public boolean isEmailConfirmed() {
        return emailConfirmed;
    }

    /**
     * Returns if this {@link User} <code>email</code> is associated to an IME's
     * Vision Research Group account.
     * 
     * @return <code>true</code> if this {@link User} <code>email</code> is
     *         associated to an IME's Vision Research Group account
     */
    public boolean isVisionUser() {
        return getEmail().endsWith("@escience.ime.usp.br");
    }

    /**
     * Tests <code>otherPassword</code> has the same crypto signature.
     * 
     * @param otherPassword
     * @return
     */
    public boolean samePassword(final String otherPassword) {
        return CryptoUtils.encrypt(otherPassword).equals(getPassword());
    }

    public void setAccountAuthorized(final boolean accountAuthorized) {
        this.accountAuthorized = accountAuthorized;
    }

    public void setActive(final boolean active) {
        this.active = active;
    }

    public void setDateCreation(final Date dateCreation) {
        this.dateCreation = dateCreation;
    }

    public void setDateUpdate(final Date dateUpdate) {
        this.dateUpdate = dateUpdate;
    }

    public void setEmail(final String email) {
        this.email = email;
    }

    public void setEmailConfirmed(final boolean emailConfirmed) {
        this.emailConfirmed = emailConfirmed;
    }

    public void setId(final int id) {
        this.id = id;
    }

    public void setName(final String name) {
        this.name = name;
    }

    public void setPassword(final String password) {
        this.password = password;
    }

    public void setPermission(final int permission) {
        this.permission = permission;
    }

    public void setUsername(final String username) {
        this.username = username;
    }

    @Override
    public String toString() {
        return "User [id=" + id + ", username=" + username + ", permission="
                + getPermissionString() + ", name=" + name + ", email=" + email
                + ", emailConfirmed=" + emailConfirmed + ", accountAuthorized="
                + accountAuthorized + ", active=" + active + ", dateCreation="
                + dateCreation + ", dateUpdate=" + dateUpdate + "]";
    }

}

src/main/java/br/usp/ime/vision/dataset/actions/UnauthorizedAction.java
package br.usp.ime.vision.dataset.actions;

import br.usp.ime.vision.dataset.util.Messages;

/**
 * Action utilized in case of requests that the current user does'nt have the
 * necessary permissions.
 * 
 * @author Bruno Klava
 */
public class UnauthorizedAction extends AbstractAction {

    private static final long serialVersionUID = 1L;

    @Override
    public String execute() throws Exception {
        addActionError(Messages.getMessage("unauthorizedAction"));
        return SUCCESS;
    }

}

src/main/java/br/usp/ime/vision/dataset/actions/tag/AlbumTagAction.java
package br.usp.ime.vision.dataset.actions.tag;

import java.util.List;

import br.usp.ime.vision.dataset.actions.album.AlbumAction;
import br.usp.ime.vision.dataset.dao.DAOFactory;
import br.usp.ime.vision.dataset.entities.Tag;

/**
 * Action to populate the view with {@link Tag}s.
 * 
 * @author Bruno Klava
 */
public class AlbumTagAction extends AlbumAction {

    private static final long serialVersionUID = 1L;

    private List<String> tags;

    @Override
    public String execute() throws Exception {

        if (!isUserHasCreatePermission()) {
            return UNAUTHORIZED_ACTION;
        }

        return SUCCESS;

    }

    public List<String> getTags() {
        if (tags == null) {
            tags = DAOFactory.getTagDao().getTagsNames();
        }
        return tags;
    }

}

src/main/webapp/album.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="/struts-tags" prefix="s"%>
<%@ taglib uri="/WEB-INF/tld/vision.tld" prefix="v"%>

<jsp:useBean id="Constants"
	class="br.usp.ime.vision.dataset.util.Constants" scope="session" />

<c:choose>

	<c:when test="${!userHasViewPermission}">
		<s:action name="UnauthorizedAction" executeResult="true" />
	</c:when>

	<c:otherwise>

		<s:set var="deleteImageText">
			<s:text name="deleteImage" />
		</s:set>
		<s:set var="deleteAlbumText">
			<s:text name="deleteAlbum" />
		</s:set>
		<s:set var="deleteTagText">
			<s:text name="deleteAlbumTag" />
		</s:set>
		<s:set var="renameTagText">
			<s:text name="renameTag" />
		</s:set>

		<tiles:insertDefinition name="templateVisionDataset">
			<tiles:putAttribute name="content">

				<h1>
					<s:url action="ListAlbums" var="listAlbums" />
					<a href="${listAlbums}"><s:text name="listAlbums" /> </a> <img
						src="img/icons/breadcrumb.png" alt=">" />

					<c:forEach items="${album.parents}" var="parentAlbum">

						<s:url var="linkAction" action="AlbumDetail">
							<s:param name="albumId">${parentAlbum.id}</s:param>
						</s:url>
						<a href="${linkAction}"> ${parentAlbum.name} </a>

						<img src="img/icons/breadcrumb.png" alt=">" />

					</c:forEach>

					${album.name}
				</h1>

				<div class="section">

					<s:set var="menu">
						<s:text name="menu" />
					</s:set>
					<v:optionsMenu name="${menu}" icon="img/icons/menu.png">

						<ul>

							<c:if test="${!empty album.tags || userHasCreatePermission}">

								<li class="tagOption show"><a href="#"
									onclick="showTags();"> <img src="img/icons/tag.png"
										alt="<s:text name="showAlbumTags"/>" /> <s:text
											name="showAlbumTags" /> </a>
								</li>

								<li class="tagOption hide" style="display: none"><a
									href="#" onclick="hideTags();"> <img
										src="img/icons/tag.png" alt="<s:text name="hideAlbumTags"/>" />
										<s:text name="hideAlbumTags" /> </a>
								</li>

							</c:if>

							<c:if test="${sessionScope.user.admin}">
								<li><s:url action="ChangeAlbumOwnerData"
										var="changeAlbumOwner">
										<s:param name="albumId">${album.id}</s:param>
									</s:url> <s:set var="changeAlbumOwnerText">
										<s:text name="changeAlbumOwner" />
									</s:set> <a href="${changeAlbumOwner}"><img
										alt="${changeAlbumOwner}" src="img/icons/owner.png" />${changeAlbumOwnerText}</a>
								</li>
							</c:if>

							<c:if
								test="${sessionScope.user.id == album.ownerId || sessionScope.user.admin}">
								<c:if test="${album.rootAlbum}">
									<li><s:url action="EditAlbumPermissionsData"
											var="editAlbumPermissions">
											<s:param name="albumId">${album.id}</s:param>
										</s:url> <s:set var="editAlbumPermissionsText">
											<s:text name="editAlbumPermissions" />
										</s:set> <a href="${editAlbumPermissions}"><img
											alt="${editAlbumPermissionsAlbum}"
											src="img/icons/password.png" />${editAlbumPermissionsText}</a>
									</li>
								</c:if>
							</c:if>

							<c:if test="${userHasCreatePermission}">

								<li><s:url action="RenameAlbumData" var="renameAlbum">
										<s:param name="albumId">${album.id}</s:param>
									</s:url> <s:set var="renameAlbumText">
										<s:text name="renameAlbum" />
									</s:set> <a href="${renameAlbum}"><img alt="${renameAlbumText}"
										src="img/icons/edit.png" />${renameAlbumText}</a>
								</li>

								<li><s:url action="UploadImageData" var="uploadImage">
										<s:param name="albumId">${album.id}</s:param>
									</s:url> <s:set var="uploadImageText">
										<s:text name="uploadImage" />
									</s:set> <a href="${uploadImage}"><img alt="${uploadImageText}"
										src="img/icons/new-image.png" />${uploadImageText}</a>
								</li>

								<li><s:url action="CreateSubAlbumData" var="createSubAlbum">
										<s:param name="parentId">${album.id}</s:param>
									</s:url> <s:set var="createSubAlbumText">
										<s:text name="createSubAlbum" />
									</s:set> <a href="${createSubAlbum}"><img
										alt="${createSubAlbumText}" src="img/icons/new-album.png" />${createSubAlbumText}</a>
								</li>

								<li><s:url action="DeleteAlbum" var="deleteAlbum">
										<s:param name="albumId">${album.id}</s:param>
									</s:url> <a href="#"
									onclick="confirmDelete('${deleteAlbumText}', ' ${album.name}', '${deleteAlbum}'); return false;">
										<img alt="${deleteAlbumText}" src="img/icons/delete.png" />${deleteAlbumText}
								</a>
								</li>

								<li><s:url action="MultiTagData" var="multiTag">
										<s:param name="albumId">${album.id}</s:param>
									</s:url> <s:set var="multiTagText">
										<s:text name="multiTag" />
									</s:set> <a href="${multiTag}"><img alt="${multiTagText}"
										src="img/icons/multitag.png" />${multiTagText}</a>
								</li>

								<c:if test="${!album.emptyAlbum}">
									<li><s:url action="MoveAlbumContentData"
											var="moveAlbumContent">
											<s:param name="albumId">${album.id}</s:param>
										</s:url> <s:set var="moveAlbumContentText">
											<s:text name="moveAlbumContent" />
										</s:set> <a href="${moveAlbumContent}"><img
											alt="${moveAlbumContentText}" src="img/icons/move.png" />${moveAlbumContentText}</a>
									</li>
								</c:if>

							</c:if>

						</ul>

					</v:optionsMenu>

					<c:if test="${!empty album.tags || userHasCreatePermission}">

						<table class="data-view tags">
							<tr>
								<th><img src="img/icons/tag.png"
									alt="<s:text name="albumTags"/>" /> <s:text name="albumTags" />
								</th>
							</tr>
							<tr>
								<td><c:if test="${userHasCreatePermission}">
										<s:url action="AddAlbumTagData" var="addAlbumTag">
											<s:param name="albumId">${album.id}</s:param>
										</s:url>
										<s:set var="addAlbumTagText">
											<s:text name="addAlbumTag" />
										</s:set>
										<a href="${addAlbumTag}" title="${addAlbumTagText}"><img
											alt="${addAlbumTagText}" src="img/icons/add-tag.png" /> </a>
									</c:if> <c:forEach var="tag" items="${album.tags}">
										<span class="tag"> ${tag.tagName} <c:if
												test="${userHasCreatePermission}">
												<s:url action="DeleteAlbumTag" var="deleteTag">
													<s:param name="tagId">${tag.id}</s:param>
													<s:param name="albumId">${album.id}</s:param>
												</s:url>
												<s:url action="RenameAlbumTagData" var="renameTag">
													<s:param name="tagId">${tag.id}</s:param>
													<s:param name="albumId">${album.id}</s:param>
												</s:url>
												<span class="tagOptions"> <a href="#"
													onclick="confirmDelete('${deleteTagText}', '${tag.tagName}','${deleteTag}'); return false;"
													title="${deleteTagText}"> <img alt="${deleteTagText}"
														src="img/icons/remove-tag.png" /> </a> <a href="${renameTag}"
													title="${renameTagText}"> <img alt="${renameTagText}"
														src="img/icons/edit-tag.png" /> </a> </span>
											</c:if> </span>
									</c:forEach>
								</td>
							</tr>
						</table>

					</c:if>

					<c:if test="${!empty album.subAlbums}">

						<table class="data-view">
							<tr>
								<th><s:text name="album.name" /></th>
								<th><s:text name="album.dateCreation" /></th>
								<th><s:text name="album.dateUpdate" /></th>
							</tr>
							<c:forEach var="subAlbum" items="${album.subAlbums}">
								<tr>
									<td><s:url var="linkAction" action="AlbumDetail">
											<s:param name="albumId">${subAlbum.id}</s:param>
										</s:url> <a href="${linkAction}" title="<s:text name="viewAlbum" />">

											<img src="img/icons/album.png" alt="<s:text name="album"/>" />
											<c:out value="${subAlbum.name}" /> </a>
									</td>
									<td><fmt:formatDate value="${subAlbum.dateCreation}"
											pattern="${Constants.datePattern}" /></td>
									<td><fmt:formatDate value="${subAlbum.dateUpdate}"
											pattern="${Constants.datePattern}" /></td>
								</tr>
							</c:forEach>
						</table>

					</c:if>

					<c:if test="${empty album.images}">
						<s:text name="noImages" />
					</c:if>

					<c:forEach items="${album.images}" var="image">

						<c:choose>

							<c:when test="${userHasCreatePermission}">
								<s:url action="DeleteImage" var="delete">
									<s:param name="imageId">${image.id}</s:param>
									<s:param name="albumId">${album.id}</s:param>
								</s:url>
								<v:thumbnail image="${image}" delete="${delete}"
									deleteText="${deleteImageText}" />
							</c:when>

							<c:otherwise>
								<v:thumbnail image="${image}" />
							</c:otherwise>

						</c:choose>

					</c:forEach>

				</div>

				<div class="confirmDialog" id="confirmDeleteDialog">
					<p class="warning">
						<s:text name="operationCannotBeUndone" />
					</p>
				</div>

			</tiles:putAttribute>

			<tiles:putAttribute name="pageScript">
				animateMenu();
				$(document).ready(function() {
					
					if($.cookie("showTags")){
						showTags(true);
					}
					
				});
			</tiles:putAttribute>

		</tiles:insertDefinition>

	</c:otherwise>

</c:choose>

src/main/webapp/home.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib prefix="s" uri="/struts-tags"%>

<tiles:insertDefinition name="templateVisionDataset">
	<tiles:putAttribute name="content">

		<h1>HOME...</h1>

		<c:if test="${sessionScope.user == null}">

			<div id="infoHome">

				<div class="action">
					<p>
						<s:text name="createAccount.help" />
					</p>
					<s:url action="SignUp" var="signUp" />
					<c:set var="signUpText">
						<s:text name="createAccount" />
					</c:set>
					<a href="${signUp}"><img alt="${signUpText}"
						src="img/icons/new-user.png" />${signUpText}</a>
				</div>

				<div class="action">
					<p>
						<s:text name="passwordLost.help" />
					</p>
					<s:url action="PasswordRecovery" var="passwordLost" />
					<c:set var="passwordLostText">
						<s:text name="passwordLost" />
					</c:set>
					<a href="${passwordLost}"><img alt="${passwordLostText}"
						src="img/icons/password.png" />${passwordLostText}</a>
				</div>

			</div>

		</c:if>

	</tiles:putAttribute>
</tiles:insertDefinition>